### ISSUE TITLE
Unable to Release v3.5.0

### ISSUE THREAD

**Issue by danthony06** [ros2-gbp/marti_common-release#2]
@nuclearsandwich I managed to release this for Humble and Rolling. I'm trying to release for Galactic now, but I'm getting an error when pushing to the release repo, because the remote contains work that I do not have locally. I've attached the full output from my release attempt.
[galactic_bloom.txt](https://github.com/ros2-gbp/marti_common-release/files/9759924/galactic_bloom.txt)

**Comment by tfoote** [comment]
@danthony06 you might have hit a race condition that someone else made a PR while yours was in flight. I'd suggest trying again with `--pull-request-only` to just try that part again.

**Comment by danthony06** [comment]
@tfoote I see that Humble's distribution.yaml file now has a 3.5.0 version, but it's referencing the wrong branch. Can I issue a PR to fix this without bumping the version number, or do I need to do the entire release again?

**Comment by tfoote** [comment]
You can always change the reference, but if bloom put that version there, it likely pulled from the other branch. Changing the reference will only change future releases. If the branch that it's referencing is fine for the last release you can just change the reference. If it's not correct for 3.5.0 that you just released you need to do another release with the real content that you want at a higher version number.

**Comment by danthony06** [comment]
@tfoote I'm not sure if I did this right, but I opened a PR for foxy here with ```--pull-request-only```. For some reason, it keeps wanting to release 3.4.1, so I manually bumped the version numbers. https://github.com/ros/rosdistro/pull/35471
