### ISSUE TITLE
Unblock Builds in Humble

### ISSUE THREAD

**Issue by danthony06** [ros2-gbp/marti_common-release#4]
@clalancette this hasn't been getting built for quite a while because the builds were blocked. I fixed this a while ago, and it should not get unblocked. It's blocking several downstream projects, notably https://github.com/ros2-gbp/mapviz-release/issues/2, which is now becoming a bigger issue because they'd like to use Mapviz as part of a Nav2 tutorial.

**Comment by clalancette** [comment]
I've opened https://github.com/ros2/ros_buildfarm_config/pull/281 , which should un-blacklist it once it is merged.  As an FYI, you are free to open PRs like that in the future.

**Comment by danthony06** [comment]
Thanks, I didn't realize that was possible.
